apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dov-as
  namespace: dovns
  labels:
    app:  default
    name: dov-as
spec:
   minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dov-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50