---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: myns
  labels:
    app: mysql
    name: mysql-pvc
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: myns
  labels:
    app: mysql
    name: mysql-deploy
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: mysql
      name: mysql-pod
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
        name: mysql-pod
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
      containers:
      - name: mysql-container
        image: mysql:8
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeit
        ports: 
        - containerPort: 3306
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/mysql