---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy-1
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-deploy-1
spec:
  replicas: 1
  selector:
    matchLabels: # this means the pods with these labels belongs to this deployment
      app: bgg
      name: bggdb-pod
  template:
    # the pod template
    metadata:
      name: bggdb-pod
      # namespace: bggns
      labels:
        app: bgg
        name: bggdb-pod
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggdb-pod
  ports:
  - protocol: TCP
    port: 3306 # this is the port that the service listens on (service port)
    targetPort: 3306 # this is the port that the service forwards to (container port)