---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggdb-pod
  ports:
  - protocol: TCP
    port: 3306 # this is the port that the service listens on (service port)
    targetPort: 3306 # this is the port that the service forwards to (container port)
  

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-svc
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggapp-pod
  ports:
  - protocol: TCP
    port: 3000 # this is the port that the service listens on (service port)
    targetPort: 3000 # this is the port that the service forwards to (container port)
  