networks:
  mynet:

volumes:
  myvol:

services:
  mydb:
    image: stackupiss/northwind-db:v1
    networks:
      - mynet
    volumes:
      - myvol:/var/lib/mysql

  myapp:
    image: stackupiss/northwind-app:v1
    environment:
      - DB_HOST=mydb
      - DB_USER=root
      - DB_PASS=changeit
    networks:
      - mynet
    ports:
      - 8080:3000
    depends_on:
      - mydb
    