---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio-ns
  labels:
    app: minio
    name: minio-cm
data:
  MINIO_ROOT_USER: minio-root-user
  MINIO_ROOT_PASSWORD: minio-root-password
  MINIO_DATA_DIR: /bitnami/minio/data
  MINIO_CI_CD: "1"