---
apiVersion: v1
kind: Pod
metadata:
  name: dov-po
  namespace: myns
  labels:
    app: dov
    name: dov-po
spec:
  containers:
  - name: dov-container
    image: chukmunnlee/cfdsa-dov-bear:v1.1
    imagePullPolicy: IfNotPresent
    env:
    - name: INSTANCE_NAME
      value: hello
    - name: INSTANCE_HASH
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports: 
    - containerPort: 3000
    livenessProbe: # health check
      httpGet:
        path: /healthz
        port: 3000
